# NumPy

> CONTENTS:
* Working with numerical data in Python
* Going from Python lists to Numpy arrays
* Multi-dimensional Numpy arrays and their benefits
* Array operations, broadcasting, indexing, and slicing
* Working with CSV data files using Numpy

## Numerical Computing With Python and Numpy :

![](https://i.imgur.com/mg8O3kd.png)

This tutorial series is a beginner-friendly introduction to programming and data analysis using the Python programming language. These tutorials take a practical and coding-focused approach. The best way to learn the material is to execute the code and experiment with it yourself.

### Working with numerical data:

The "data" in *Data Analysis* typically refers to numerical data, **e.g.- Stock Price, Sales, figures, Sensor Measurements, Sports Scores, Database Tables, etc.** The [NumPy](https://numpy.org) library provides specialized data structures, functions and other tools for numerical computing in Python. Let's work through an example to see why and how to use Numpy for working  with numerical data.
> Suppose we want to use climate data like `temprature`, `rainfall`, and `humidity` to determine if a region is well suited for growing apples. A simple approach for doining this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degree Fahrenheit), rainfall (in millimeters) and average relative humidity (in percentage) as linear equation:
>
>` yield_of_apples = w1 * temprature + w2 * rainfall + w3 * humidity`
        
We are expressing the yield of apples as a weighted sum of the temperature, rainfall, and humidity. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.  

Based on some statical analysis of historical data, we might come up with reasonable values for the weights `w1`, `w2` & `w3`. Here's an example of values:

In [3]:
w1, w2, w3 = .3,.2,.5

**Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:**

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

**To begin, we can define some variables to record climate data for a region.**

In [4]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

**We can now substitute these variables into the linear equation to predict the yield of apples.**

In [5]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
print("Kanto's expected yield of apples :", kanto_yield_apples,"(in tones per hectare)")

Kanto's expected yield of apples : 56.8 (in tones per hectare)


> **To make slightly easier to perform the above computation for multiple regions, we can represent the climate data for each regions, we can represent the climate data for each region as a vector, i.e.- a list of numbers.**

In [6]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]

**The three numbers in each vector represent the *temperature, rainfall, and humidity* data, respectively.**  

**We can also represent the set of weights used in the formula as a vector.**

In [7]:
weights = [w1,w2,w3]

**We can now write a function `crop_yield` to calculate the yield of apples(or any other crop) given the climate data and the respective weights.**

In [8]:
def crop_yield(region,weight):
    result = 0
    for x,w in zip(region,weight):
        result += x*w
    return result

In [9]:
kanto_yield = crop_yield(region=kanto,weight=weights)
print("Crop yield in Kanto region :",kanto_yield)

Crop yield in Kanto region : 56.8


In [10]:
johto_yield = crop_yield(region=johto,weight=weights)
print("Crop yield in Johto region :",johto_yield)

Crop yield in Johto region : 76.9


In [11]:
hoenn_yield = crop_yield(region=hoenn,weight=weights)
print("Crop yield in Hoenn region :",hoenn_yield)

Crop yield in Hoenn region : 81.9


In [12]:
import math
sinnoh_yield = crop_yield(region=sinnoh,weight=weights)
print("Crop yield in Sinnoh region :","%.2f" % round(sinnoh_yield,1))

Crop yield in Sinnoh region : 57.70


In [13]:
unova_yield = crop_yield(region=unova,weight=weights)
print("Crop yield in Unova region :",unova_yield)

Crop yield in Unova region : 74.9


> **The calculation performed by the `crop_yield` (element-wise multiplication of two vectors and taking a sum of the results) is also called the *dot product*. [Learn more about dot product here](https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length).**

## Going from Python lists to NumPy
The Numpy library provides a built-in function to compute the dot product of two vectors. However, we must first convert the lists into Numpy arrays.

**Let's install the Numpy library using `!pip install numpy --upgrade --quiet`. Here `pip` is a package manager.**

In [ ]:
!pip install numpy --upgrade --quiet

**Next, let's `improt` the `numpy` module. It's common practice to import numpy with the *alias (short form to use again)* `np`.**

In [16]:
import numpy as np

**We can now use the `np.arry` function to create Numpy arrays.**

In [17]:
kanto = np.array([73,67,43])
print(kanto)

[73 67 43]


In [18]:
# See the difference between `print(kanto)` and `kanto`
kanto

array([73, 67, 43])

In [19]:
weights = np.array([w1,w2,w3])
weights

array([0.3, 0.2, 0.5])

**Numpy array have the type `ndarray`.**

In [20]:
type(kanto)

numpy.ndarray

In [21]:
type(weights)

numpy.ndarray

**Just like lists, Numpy arrays support the indexing notation `[]`.**

In [22]:
weights[0]

0.3

In [23]:
kanto[2]

43

## Operating on Numpy arrays

We can now compute the dot product of the two vectors using the `np.dot` function.

In [24]:
# Method-1 (Advance-Level)

np.dot(kanto,weights)

56.8

> **Explanation :-** The `*` operator performs an element-wise multiplication of two arrays if they have the same size. The `sum` method calculates the sum of numbers in an array.

In [25]:
# See the calculation:

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [26]:
# multiplication `*`

arr1 * arr2

array([ 4, 10, 18])

In [27]:
# Sumation `.sum()`

arr1.sum()

6

### Benefits of using Numpy arrays:

Numpy array offer the following benefits over Python lists for operating on numerical data:

* **Ease Of Use:-** You can write small, concise, and intuitive mathematical expressions like `(kanto*weights).sum()` rather than using loops and custom functions like `crop_yield`.
* **Performance:-** Numpy operations and functions are implemented initially in C++, which makes them much faster than using Python statements and loops that are interpreted at runtime

**Here is a comparison of dot products performed using Python loops vs Numpy array on two vectors with a million elements each.**

In [28]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [29]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 150 ms, sys: 0 ns, total: 150 ms
Wall time: 149 ms


833332333333500000

In [30]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: user 2.85 ms, sys: 0 ns, total: 2.85 ms
Wall time: 1.69 ms


833332333333500000

* As you can see, using `np.dot` is 100 times faster than using a fokr loop. This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.  

Let's save our work before continuing:

## Multi-dimensional Numpy arrays:

We can now go one step further and represent the climate data for all the regions using a single 2-dimensional Numpy array.

In [32]:
import numpy as np

climate_data = np.array([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]
                        ])

In [33]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

* If you've taken a linear algebra class in high school, you may recognize the above 2-D array as a matrix with five rows and three columns. Each row represents one region, and the columns represent temperature, rainfall, and humidity, respectively.

Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">

In [34]:
# 2-D array (or matrix)
climate_data.shape

(5, 3)

In [35]:
weights

array([0.3, 0.2, 0.5])

In [36]:
# 1-D array (or vector)
weights.shape

(3,)

In [37]:
# 3-D array
arr3 = np.array([
    [[11,12,13],
    [13,14,15]],
    [[15,16,17],
    [17,18,19.5]]
])

In [38]:
arr3.shape

(2, 2, 3)

**All the elements in a numpy array have the same data type. You can check the data type of an array using the `.dtype` property.**

In [39]:
weights.dtype

dtype('float64')

In [40]:
climate_data.dtype

dtype('int64')

**If an array contains even a single floating point number, all the other elements are also converted to floats.**

In [41]:
arr3.dtype

dtype('float64')

We can now compute the predicted yield of apples in all the regions, using a single matrix multiplication between `climate_data` (a 5×3 matrix) and `weights` (a vector of length 3). Here's what it looks like visually:

<img src="https://i.imgur.com/LJ2WKSI.png" width="240">

You can learn about matrices and matrix multiplication by watching the first 3-4 videos of this [playlist](https://www.youtube.com/watch?v=xyAuNHPsq-g&list=PLFD0EB975BA0CC1E0&index=1).  

We can use the `np.matmul` function or the `@` operator to perform matrix multiplication.

In [42]:
# Matrix multiplication or `.matmul` function.
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [43]:
# Matrix multiplication or dot product or @ operation.
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

## Working with CSV (Comma Separated Value) data files:

Numpy also provides helper functions reading from and writing to files. Let's download a file `climate.txt`, which contains 10,000 climate measurements (temperature, rainfall and humidity) in the following formate:

```
temperature, rainfall, humidity
25.00, 76.00, 99.00
39.00, 35.00, 70.00
59.00, 45.00, 77.00
84.00, 63.00, 38.00
66.00, 50.00, 52.00
41.00, 94.00, 77.00
91.00, 57.00, 96.00
49.00, 96.00, 99.00
67.00, 20.00, 28.00
...
```

This formate of storing data is known as *comma-separated-value* or CSV.

> **CSVs :-** A comma-separated value (CSV) file is determined text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields,separated by commas.A CSV file typically stores tabular data (number and text) in plain text, in which case each line will have the same number of fields.

**To read this file into a numpy array, we can use the `genfromtext` function.**

In [44]:
import urllib.request

urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f5c22d8d430>)

In [45]:
climate_data = np.genfromtxt('climate.txt',delimiter = ',',skip_header = 1)

In [46]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [47]:
climate_data.shape

(10000, 3)

**We can now perform a matrix multiplication using the `@` operator to predict the yield of apples for the entire dataset using a given set of weights.**

In [48]:
weigths = np.array([.3,.2,.5])
weights

array([0.3, 0.2, 0.5])

In [49]:
yields = climate_data @ weights

In [50]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [51]:
yields.shape

(10000,)

**Let's add the `yields` to `climate_data` as a fourth column using the `np.concatenate` function.**

In [52]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)), axis=1)

In [53]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

> There are a couple of subtleties here:
>  
> * Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`.The `axis` argument specifies the dimension of concatenation.
> * The array should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the `np.reshape` function to change the shape of `yields` from `(10000,)` to `(10000,1)`.


**Here is a visual explanation of `np.conacatenate` along `axis=1` (can you guess what `axis=0` result in?)**

<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">

**The best way to understand what a Numpy function does is to experiment with it and read the documentation to learn about it's arguments and return values. Use the cells below to experiment with `np.concatenate` and `np.reshape`.**

In [54]:
import numpy as np

arr1 = np.array([[0,1,2],[5,7,9]])
arr2 = np.array([[0,2,4],[6,8,10]])

In [55]:
arr1

array([[0, 1, 2],
       [5, 7, 9]])

In [56]:
arr2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [57]:
np.concatenate((arr1,arr2),1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [58]:
np.concatenate((arr1,arr2),0)

array([[ 0,  1,  2],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [59]:
a=np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
np.reshape(a, 6)

array([0, 1, 2, 3, 4, 5])

In [62]:
np.reshape(a, 6, order='F')

array([0, 3, 1, 4, 2, 5])

In [63]:
np.reshape(a, (3,-1))       # the unspecified value is inferred to be 2

array([[0, 1],
       [2, 3],
       [4, 5]])

**Let's write the final results from our computation above back to file using the `np.savetext` function.**

In [64]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [65]:
np.savetxt('climate_result..txt',
          climate_results,
          fmt = '%.2f',
          delimiter = ',',
          header = 'temperature, rainfall, humidity, yield_apples',
          comments = '')

**The results are written back in the CSV formate to the file `climate_results.txt`.**

```
temperature, rainfall, humidity, yield_apples
25.00, 76.00, 99.00, 72.20
39.00, 65.00, 70.00, 59.00
59.00, 45.00, 77.00, 65.20
84.00, 63.00, 38.00, 56.00
...

```

**Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used function:**

* Mathematics: `np.sum`, `np.exp`,`np.round`, arithmetic operators
* Array manipulation: `np.reshape`, `np.stack`,`np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`,`np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How To Find The Function You Need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for " How to join numpy arrays" leads to [This Tutorial On Array Concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/).  
>
> **You can find a full list of array function - [Click Here](https://numpy.org/doc/stable/reference/routines.html).**


## Arithmetic Operations, Broadcasting and Comparison:

Numpy array support arithmetic operators like- `+`, `-`,`*`, `/`, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

### 1. Arithmetic Operations:

In [67]:
arr_1= np.array([[1,2,3,4],
                [5,6,7,8],
                [9,1,2,3,]])

In [68]:
arr_2=np.array([[11,12,13,14],
               [15,16,17,18],
               [19,11,12,13]])

In [69]:
# Adding a scalar

arr_1 + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14,  6,  7,  8]])

In [70]:
# Element-wise substraction

arr_1 - arr_2

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [71]:
# Scalar Substraction

arr_1 - 1

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 0, 1, 2]])

In [72]:
# Division by scalar

arr_1 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [73]:
# Element-wise multiplication

arr_1 * arr_2

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [74]:
# Modulus with scalar

arr_2 % 4

array([[3, 0, 1, 2],
       [3, 0, 1, 2],
       [3, 3, 0, 1]])

In [75]:
arr_1%5

array([[1, 2, 3, 4],
       [0, 1, 2, 3],
       [4, 1, 2, 3]])

### 2. Array Broadcasting:

Numpy array also support *broadcasting*, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.

In [76]:
arr_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [77]:
arr_1.shape

(3, 4)

In [78]:
arr_3 = np.array([9,5,1,3])

In [79]:
arr_3.shape

(4,)

In [80]:
arr_1 + arr_3

array([[10,  7,  4,  7],
       [14, 11,  8, 11],
       [18,  6,  3,  6]])

* **Conclusion:-** When the expression `arr_1 + arr_3` is evaluated, `arr_3` (which has the shape `(4,)`) is replicated three times to match the shape `(3,4)` of `arr_1`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

* **Broadcasting only works if one of the arrays can be replicated to match the other array's shape.**

In [81]:
arr_3 = np.array([7,8])

In [83]:
arr_3.shape

(2,)

In [84]:
arr_1 + arr_3

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

* **Conclusion:-** In the above example, even if `arr_3` is replicated thre times, it will not match the shape of `arr_1`. Hence `arr_1 + arr_3` cannot be evaluated successfully.  


* To learn more about broadcasting : [click here](https://numpy.org/doc/stable/user/basics.broadcasting.html).

### Array Comparison:
Numpy array also support comparison operation like `==`, `!=`, `>` etc. The result is an array of booleans.

In [91]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[2,2,3],[1,2,3]])

In [92]:
arr1 == arr2

array([[False,  True,  True],
       [False, False, False]])

In [93]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True,  True]])

In [94]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [95]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

**Note:-**
1. All comparison is element-wise.
2. Array comparison is frequently used to count the number of equal elements in two array using the `sum` method. Remember that `True` evaluates to `1` and `False` evaluates to `0` when booleans are used in arithmetic operations.

In [96]:
(arr1==arr2).sum()

2

### Array indexing and slicing:
Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a sub-array (also called a slice) from a Numpy array. 

In [97]:
arr3 = np.array([
    [[11,12,13,14],
     [13,14,15,16]],
    
    [[15,16,17,18],
    [63,64,65,66]],
    
    [[19,20,27,26],
    [71,72,73,74]]
])

In [98]:
arr3.shape

(3, 2, 4)

In [99]:
# Single element
arr3[1,1,2]

65

In [100]:
arr3[0,0,0]

11

**Note:-** 
* Indexing is from Zero To N-1 as in list but it's a array or matrix form.  

```
arr_[x,y,z]

* x = width index 
                or
      index in first bracket
* y = row index 
                or
      index in second bracket
* z = column index 
                or
      index in third bracket
     
```  
* This form of command's output is a single value of array / matrix.

In [102]:
arr3

array([[[11, 12, 13, 14],
        [13, 14, 15, 16]],

       [[15, 16, 17, 18],
        [63, 64, 65, 66]],

       [[19, 20, 27, 26],
        [71, 72, 73, 74]]])

In [101]:
# Sub-array using ranges

arr3[1:, 0:1, :2]

array([[[15, 16]],

       [[19, 20]]])

In [103]:
# Mixing indices and ranges

arr3[1:, 1, :3]

array([[63, 64, 65],
       [71, 72, 73]])

In [ ]:
# Using fewer indices

arr3[1]

In [ ]:
# Using fewer indices

arr3[:3, 1]

In [105]:
# Using too many indices

arr[1,3,2,0]

NameError: name 'arr' is not defined

**The  notation and it's results can seem confusing at first, so take your time to experiment and become comfortable with it. Use the cells below to try out some examples of array indexing and slicing, with different combinations of indices and ranges. Here are some more examples demonstrated visually:**  

<img src="https://scipy-lectures.org/_images/numpy_indexing.png" width="360">

In [106]:
a = np.array([[0,1,2,3,4,5],
             [10,11,12,13,14,15],
             [20,21,22,23,24,25],
             [30,31,32,33,34,35],
             [40,41,42,43,44,45],
             [50,51,52,53,54,55]])

In [107]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [108]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [109]:
a[0,3:5]

array([3, 4])

In [110]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [111]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [113]:
a[2::2,2::2]

array([[22, 24],
       [42, 44]])

In [114]:
a[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

## Other ways of creating Numpy arrays
Numpy also provides some handy to create arrays of desired shapes with fixed or random values. Check out the [Official Documentaion](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function or use the shortcut key `Shift + Tab` to learn more.

In [115]:
# All zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [116]:
# All ones
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [117]:
# Identity Matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [118]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
# Random vector
np.random.rand(5)

# note- this produce a random vector with 5 value i.e. columns.

array([0.91739278, 0.03187741, 0.5090057 , 0.09318413, 0.03397519])

In [121]:
# Random matrix
np.random.rand(2,3)

array([[0.39610102, 0.38906641, 0.93856208],
       [0.69755859, 0.70105902, 0.7077818 ]])

> **Difference between `.rand()` and `randn()` :-** 
> * `.rand()` - Used for number of random value i.e `columns`.
> * `.randn()` - Used with two `arguments First` one is for number of `rows` and `argument Second` one for number of `columns`.   
> * Note that the default random values are between 0 and 1. We will see further how to set required random values.

In [122]:
# Fixed value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [124]:
# Range with start(1st argument), end(2nd argument) and step(3rd argument)
np.arange(10,90,3)


array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [126]:
# Equally spaced numbers in a range
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

## Exercises:
**Trying the following exercises to become familiar with Numpy arrays:**

* Assignment On Numpy array functions : [click here](https://jovian.ai/aakashns/numpy-array-operations).
* 100 Numpy Exercises: [click here](https://jovian.ai/aakashns/100-numpy-exercises).

## Summary and Further Reading:
With this, we complete our discussion of numerical computing with Numpy. We've covered the following topics in this tutorial:

* Going from Python lists to Numpy arrays
* Operating on Numpy arrays
* Benefits of using Numpy arrays over lists
* Multi-dimensional Numpy arrays
* Working with CSV data files
* Arithmetic operations and broadcasting
* Array indexing and slicing
* Other ways of creating Numpy arrays

**Check out the following resources for learning more about Numpy:**

* Official Tutorial: [Click Here](https://numpy.org/devdocs/user/quickstart.html).
* Numpy Tutorial On W3Schools: [Click Here](https://www.w3schools.com/python/numpy_intro.asp).
* Advanced Numpy (exploring the internals): [Click Here](http://scipy-lectures.org/advanced/advanced_numpy/index.html).


## Questions for Revision

Try answering the following questions to test your understanding of the topics covered in this notebook:

1. What is a vector?
2. How do you represent vectors using a Python list? Give an example.
3. What is a dot product of two vectors?
4. Write a function to compute the dot product of two vectors.
5. What is Numpy?
6. How do you install Numpy?
7. How do you import the `numpy` module?
8. What does it mean to import a module with an alias? Give an example.
9. What is the commonly used alias for `numpy`?
10. What is a Numpy array?
11. How do you create a Numpy array? Give an example.
12. What is the type of Numpy arrays?
13. How do you access the elements of a Numpy array?
14. How do you compute the dot product of two vectors using Numpy?
15. What happens if you try to compute the dot product of two vectors which have different sizes?
16. How do you compute the element-wise product of two Numpy arrays?
17. How do you compute the sum of all the elements in a Numpy array?
18. What are the benefits of using Numpy arrays over Python lists for operating on numerical data?
19. Why do Numpy array operations have better performance compared to Python functions and loops?
20. Illustrate the performance difference between Numpy array operations and Python loops using an example.
21. What are multi-dimensional Numpy arrays? 
22. Illustrate the creation of Numpy arrays with 2, 3, and 4 dimensions.
23. How do you inspect the number of dimensions and the length along each dimension in a Numpy array?
24. Can the elements of a Numpy array have different data types?
25. How do you check the data type of the elements of a Numpy array?
26. What is the data type of a Numpy array?
27. What is the difference between a matrix and a 2D Numpy array?
28. How do you perform matrix multiplication using Numpy?
29. What is the `@` operator used for in Numpy?
30. What is the CSV file format?
31. How do you read data from a CSV file using Numpy?
32. How do you concatenate two Numpy arrays?
33. What is the purpose of the `axis` argument of `np.concatenate`?
34. When are two Numpy arrays compatible for concatenation?
35. Give an example of two Numpy arrays that can be concatenated.
36. Give an example of two Numpy arrays that cannot be concatenated.
37. What is the purpose of the `np.reshape` function?
38. What does it mean to “reshape” a Numpy array?
39. How do you write a numpy array into a CSV file?
40. Give some examples of Numpy functions for performing mathematical operations.
41. Give some examples of Numpy functions for performing array manipulation.
42. Give some examples of Numpy functions for performing linear algebra.
43. Give some examples of Numpy functions for performing statistical operations.
44. How do you find the right Numpy function for a specific operation or use case?
45. Where can you see a list of all the Numpy array functions and operations?
46. What are the arithmetic operators supported by Numpy arrays? Illustrate with examples.
47. What is array broadcasting? How is it useful? Illustrate with an example.
48. Give some examples of arrays that are compatible for broadcasting?
49. Give some examples of arrays that are not compatible for broadcasting?
50. What are the comparison operators supported by Numpy arrays? Illustrate with examples.
51. How do you access a specific subarray or slice from a Numpy array?
52. Illustrate array indexing and slicing in multi-dimensional Numpy arrays with some examples.
53. How do you create a Numpy array with a given shape containing all zeros?
54. How do you create a Numpy array with a given shape containing all ones?
55. How do you create an identity matrix of a given shape?
56. How do you create a random vector of a given length?
57. How do you create a Numpy array with a given shape with a fixed value for each element?
58. How do you create a Numpy array with a given shape containing randomly initialized elements?
59. What is the difference between `np.random.rand` and `np.random.randn`? Illustrate with examples.
60. What is the difference between `np.arange` and `np.linspace`? Illustrate with examples.